---
# tasks file for argocli
- name: Copy argocli wrapper script
  template:
    src: argo.j2
    dest: ~/bin/argo
    mode: '0755'

- name: Check for updates
  lineinfile:
    path: ~/bin/update
    line: docker pull {{ argo_docker_image }}

# - name: Enable bash completion
#   lineinfile:
#     path: ~/.bashrc
#     line: 'source <(argo completion bash)'
    

