---
# tasks file for argocli
- name: Copy argocli wrapper script
  copy:
    src: argo
    dest: ~/bin/argo
    mode: '0755'

- name: 
  lineinfile:
    path: ~/.bash_profile
    regexp: 'export ARGO_VERSION='
    line: 'export ARGO_VERSION=2.7.7'
