---
# tasks file for clamav
- name: Fetch eicar.com safe virus signature file to check AV on access scanning is working
  get_url:
    url: https://secure.eicar.org/eicar.com
    dest: '/home/{{ ansible_user_id }}/Downloads/eicar.com'
    mode: '0644'
  ignore_errors: true

  # need to use clamscan user but doesn't exist yet
  #- name: Ensure log file is available for clamd
  #become: yes
  #file:
  #  path: /var/log/clamd.scan
  #  owner: clamscan
  #  state: touch
  #  mode: '0750'

  #- name: SELinux for log file
  #become: yes
  #sefcontext:
  #  target: '/var/log/clamd.scan'
  #  setype: antivirus_log_t

- name: SELinux for system
  become: yes
  seboolean:
    name: antivirus_can_scan_system
    state: yes
    persistent: yes

- include_role:
    name: geerlingguy.clamav
    apply:
      vars:
        ansible_become: yes
        clamav_daemon_configuration_changes:
            - regexp: '^.*Example$'
              state: absent
            - regexp: '^.*LocalSocket .*$'
              line: 'LocalSocket {{ clamav_daemon_localsocket }}'
            - regexp: '^.*OnAccessIncludePath /home/{{ ansible_user_id }}/Downloads$'
              line: 'OnAccessIncludePath /home/{{ ansible_user_id }}/Downloads'
            - regexp: '^.*OnAccessIncludePath /home/{{ ansible_user_id }}/bin$'
              line: 'OnAccessIncludePath /home/{{ ansible_user_id }}/bin'
            - regexp: '^.*OnAccessPrevention .*$'
              line: 'OnAccessPrevention yes'
            - regexp: '^.*OnAccessExcludeUname .*$'
              line: 'OnAccessExcludeUname clamscan'
            - regexp: '^.*OnAccessExtraScanning .*$'
              line: 'OnAccessExtraScanning yes'
            - regexp: '^.*VirusEvent .*$'
              line: 'VirusEvent notify-send "clamav virus detected: %v"'
              #- regexp: '^.*LogFile .*$'
              #  line: 'LogFile /var/log/clamd.scan'
            - regexp: '^.*LogFileMaxSize .*$'
              line: 'LogFileMaxSize 10M'
            - regexp: '^.*LogTime .*$'
              line: 'LogTime yes'

- name: Add clamscan to current user group for access to home directory contents
  become: yes
  user:
    name: clamscan
    groups: '{{ ansible_user_id }}'
    append: yes

- name: Allow current user group execute access to ~/Downloads
  file:
    path: '/home/{{ ansible_user_id }}'
    mode: '0750'

- name: Check for new virus signatures as part of usual update
  lineinfile:
    path: ~/bin/update
    regexp: 'freshclam'
    line: sudo freshclam

- name: Add clamonacc systemd unit
  become: yes
  copy:
    src: clamonacc.service
    dest: /etc/systemd/system/clamonacc.service

- name: Enable clamonacc service
  become: yes
  systemd:
    name: clamonacc.service
    daemon_reload: yes
    enabled: yes
    scope: system
    state: started

- name: Copy clamonacc check script
  copy:
    src: clamonacc-validate.sh
    dest: ~/bin/clamonacc-validate.sh
    mode: '0755'

- name: Check clamonacc prevents access to sample virus file
  command: '~/bin/clamonacc-validate.sh &'

- name: Check clamonacc function on login
  lineinfile:
    path: ~/.bash_profile
    regexp: clamonacc-validate.sh
    line: '~/bin/clamonacc-validate.sh &'
