---
- hosts: localhost
  become_method: sudo
  roles:
  - role: ./roles/workstation
  - role: ./roles/dev
  - role: ./roles/k8s
  - role: ./roles/chrome-browser
  - role: ./roles/slack
  - role: ./roles/vscode

