---
# tasks file for chromium-browser
- name: Install Chromium Browser
  become: yes
  dnf:
    name: chromium
    state: latest

- name: Configure Chromium Browser
  become: yes
  copy:
    src: chromium-prefs.json
    dest: /etc/chromium/policies/managed/prefs.json

- name: Disable password store for Chromium
  become: yes
  lineinfile:
    path: /usr/share/applications/chromium-browser.desktop
    regexp: '^Exec=/usr/bin/chromium-browser'
    line: 'Exec=/usr/bin/chromium-browser --password-store=basic %U'