- name: Remove unneeded packages
  become: yes
  package: name={{ item }} state=absent
  loop:
    - dnfdragora
    - asunder
    - pragha
    - xfburn
    - parole
    - claws-mail
    - pidgin
    - transmission
