---
- name: Install flatpak
  become: yes
  package: name=flatpak state=present
- name: Configure flathub
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
