- name: Remove unneeded packages
  become: yes
  dnf:
    autoremove: yes
    name:
      - dnfdragora
      - asunder
      - pragha
      - xfburn
      - parole
      - claws-mail
      - pidgin
      - transmission
      - bluez-cups
      - bluez-libs
      - bluez-obexd
      - bluez
      - xfce4-weather-plugin
      - sssd-ad
      - sssd-kcm
      - sssd-krb5
      - sssd-krb5-common
      - sssd-ldap
      - sssd-nfs-idmap
      - catfish
      - yelp
      - xscreensaver-extras
      - xscreensaver-extras-base
      - cifs-utils
      - cldr-emoji-annotation
      - clutter
      - criu
      - enchant
      - fprintd
      - glx-utils
      - gfs2-utils
      - gssdp
      - gutenprint
      - iodine-client
      - anaconda-install-env-deps
      - iscsi-initiator-utils
      - kyotocabinet-libs
      - samba-client
      - lrzsz
      - mlocate
      - ModemManager
      - nfs-utils
      - opensc
      - orage
      - pinentry
      - pipewire
      - ppp
      - pptp
      - realmd
      - reiserfs-utils
      - skkdic
      - stoken-libx
      - teamd
      - telnet
      - trousers
      - trousers-lib
      - vpnc
      - words
      ## virtualisation
      - open-vm-tools
      - hyperv-daemons
      - qemu-guest-agent
      - spice-vdagent
      - virtualbox-guest-additions
    state: absent

- name: Shutdown unnecessary services
  become: yes
  systemd:
    name: avahi-daemon.service
    enabled: no
    state: stopped
    scope: system



