---
- include_role:
    name: geerlingguy.docker
    apply:
      vars:
        ansible_become: yes
        docker_users:
          - "paul"
        docker_yum_repo_enable_test: "true"
        docker_yum_repo_enable_edge: "false"

