---
- include_role:
    name: gvillalta99.redshift
    apply:
      vars:
        ansible_become: yes
        location:
          latitude: 53
          longitude: -1

- name: Start redshift on login
  lineinfile:
    path: ~/.bash_profile
    line: 'redshift &'
