- name: Lock before suspending
  xfconf: channel=xfce4-session property='/shutdown/LockScreen' value_type=bool value=true

- name: Allow passwordless sudo
  become: yes
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^# %wheel\s+ALL=\(ALL\)\s+NOPASSWD:\s*ALL'
    line: '%wheel        ALL=(ALL)       NOPASSWD: ALL'
    validate: /usr/sbin/visudo -cf %s
    
- name: Remove existing mention of wheel group
  become: yes
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel\s+ALL=\(ALL\)\s+ALL'
    line: '# %wheel ALL=(ALL) ALL'
    validate: /usr/sbin/visudo -cf %s
