- name: XFCE Config - set theme
  xfconf: channel=xsettings property=/Net/ThemeName value_type=string value="{{ lookup('vars', 'desktop-theme', default='Adwaita') }}"
- name: XFCE Config - remove unused workspaces
  xfconf: channel=xfwm4 property=/general/workspace_count value_type=int value=1
- name: XFCE Config - capslock is a second ctrl
  copy: src=xinitrc dest="/home/paul/.xinitrc"
- name: Keyboard shortcuts
  xfconf: channel=xfce4-keyboard-shortcuts property={{ item.prop }} value_type=string value={{ item.val }}
  loop:
    - { prop: '/commands/custom/<Super>l', val: 'xflock4' }
    - { prop: '/commands/custom/<Super>t', val: 'xfce4-terminal' }
    - { prop: '/xfwm4/custom/<Super>a', val: 'tile_left_key' }
    - { prop: '/xfwm4/custom/<Super>c', val: 'tile_down_right_key' }
    - { prop: '/xfwm4/custom/<Super>d', val: 'tile_right_key' }
    - { prop: '/xfwm4/custom/<Super>e', val: 'tile_up_right_key' }
    - { prop: '/xfwm4/custom/<Super>q', val: 'tile_up_left_key' }
    - { prop: '/xfwm4/custom/<Super>w', val: 'tile_up_key' }
    - { prop: '/xfwm4/custom/<Super>x', val: 'tile_down_key' }
    - { prop: '/xfwm4/custom/<Super>z', val: 'tile_down_left_key' }
    - { prop: '/xfwm4/custom/<Super>s', val: 'maximize_window_key' }
    - { prop: '/commands/custom/<Super>F2', val: 'amixer set Master 5%-' }
    - { prop: '/commands/custom/AudioMicMute', val: 'amixer set Capture toggle' }
    - { prop: '/commands/custom/<Super>F1', val: 'amixer set Master toggle' }
    - { prop: '/commands/custom/<Super>F3', val: 'amixer set Master 5%+' }
    - prop: '/commands/custom/<Super>v'
      val: sh -c 'sleep 0.2; xdotool type --clearmodifiers "$(xclip -o -selection clipboard)"'

