---
# tasks file for k8s
- name: Add K8s repo
  become: yes
  yum_repository:
    name: kubernetes
    description: Kubernetes Repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Install kubectl
  become: yes
  dnf:
    name: kubectl
    state: present

- name: Enable kubectl autocompletion
  lineinfile:
    path: ~/.bashrc
    line: source <(kubectl completion bash)

- name: Copy kx script
  copy:
    src: kx
    dest: ~/bin/kx
    mode: '0755'