---
# tasks file for expressvpn

# from https://bugzilla.redhat.com/show_bug.cgi?id=1767564
# semanage fcontext -a -t net_conf_t /var/lib/expressvpn/resolv.conf
# restorecon -v /var/lib/expressvpn/resolv.conf
- name: Fix SELinux settings for ExpressVPN resolv.conf file
  become: yes
  sefcontext:
    target: '/var/lib/expressvpn/resolv.conf'
    setype: net_conf_t
    state: present


# - name: Install ExpressVPN RPM key
#   rpm_key:
#     key: 'https://download.expressvpn.xyz/clients/linux/expressvpn-2.4.4.19-1.x86_64.rpm.asc'
#     state: present
- name: Install ExpressVPN
  become: yes
  dnf:
    name: 'https://download.expressvpn.xyz/clients/linux/expressvpn-2.4.5.2-1.x86_64.rpm'
    state: present

- name: 
  lineinfile:
    path: ~/.bash_profile
    regexp: 'expressvpn connect'
    line: 'expressvpn connect'

