---
# tasks file for nodejs
- name: Download nvm installer
  get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh
    dest: ~/Downloads/nvm_install.sh
    mode: "0755"

- name: Install nvm
  command:
    cmd: ~/Downloads/nvm_install.sh
    creates: ~/.nvm/nvm.sh

- name: Install node-latest
  shell: source ~/.nvm/nvm.sh && nvm install --lts

