---
# tasks file for update
- name: Setup firmare updates
  become: yes
  dnf:
    name:
      - fwupd
    state: present
    
- name: Setup update script
  copy:
    src: update
    dest: ~/bin/update
    owner: paul
    group: paul
    mode: '0755'