---
# tasks file for gcloud
- name: Add gcloud repo
  become: yes
  yum_repository:
    name: google-cloud-sdk
    description: gcloud repo
    baseurl: https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Install gcloud
  become: yes
  dnf:
    name: google-cloud-sdk
    state: present

