---
# switch to cgroups v1
- include_role:
    name: jtyr.grub_cmdline
    apply:
      vars:
        ansible_become: true
        grub_cmdline_add_args:
          - systemd.unified_cgroup_hierarchy=0

# install and set up moby, docker-compose
# based on https://github.com/geerlingguy/ansible-role-docker/blob/master/tasks/main.yml
- name: Install moby and docker-compose
  become: true
  dnf:
    name:
      - moby-engine
      - docker-compose
    state: present
  notify: restart docker

- name: Ensure docker users are added to the docker group.
  become: true
  user:
    name: paul
    groups: docker
    append: true
  
- name: Ensure docker daemon is started
  become: true
  systemd:
    name: docker
    state: started
    enabled: true
  ignore_errors: true

