---
- name: Create SSH dir
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: '0700'
- name: Generate SSH key
  openssh_keypair:
    path: "{{ ansible_env.HOME }}/.ssh/id_ssh"
    type: rsa
    size: 2048

